version: '3.4'

services:
  it_helpdesk:
    ports:
        - 80:80
    image: ${DOCKER_REGISTRY-}ithelpdesk
    build:
      context: .
      dockerfile: IT_Helpdesk/Dockerfile

  maintenance_helpdesk:
    ports:
        - 81:80
    image: ${DOCKER_REGISTRY-}maintenancehelpdesk
    build:
      context: .
      dockerfile: Maintenance_Helpdesk/Dockerfile

  hr_helpdesk:
    ports:
        - 82:80
    image: ${DOCKER_REGISTRY-}hrhelpdesk
    build:
      context: .
      dockerfile: HR_Helpdesk/Dockerfile

  helpdesk_web:
    ports:
        - 84:80
    image: ${DOCKER_REGISTRY-}helpdeskweb
    build:
        context: .
        dockerfile: Helpdesk_Web/Dockerfile